version: '3.4'

services:
  traintelegrambot:
    image: traintelegrambot:latest
    environment:
      - ENV=development
    env_file: 
      - ./.dev.env
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
        - latest
