version: '3.4'

services:
  traintelegrambot:
    image: traintelegrambot:latest
    environment:
      - ENV=development
    env_file: 
      - ./.dev.env
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
        - latest
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]
    ports:
      - 5678:5678
